#!/usr/bin/env python3
"""Native symbols from the N64 map.

Two classes come out of the map instead of being stubbed:

1. Segment windows (_xSegmentRomStart/End as absolutes; RAM segments as
   sized buffers with adjacent End symbols).
2. EVERY unresolved symbol whose map address is ROM-flavored (< 0x04000000).
   The N64 link script places asset data at its ROM offset, so the game
   treats symbol addresses AS rom offsets - the linker is the asset table.
   LgunE at 0x008ed250 means "language file at rom 0x8ed250"; a 4KB stub at
   a native address meant every DMA read zeros from past ROM end.

Symbols the map places in RAM (0x8xxxxxxx) stay stubbable - they are state,
not data windows.
"""
import re
import sys
from pathlib import Path

map_path, unresolved_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
text = Path(map_path).read_text(errors="replace")

seg = {}
addr = {}
if text.startswith("# sightline linkmap"):
    # The tracked extraction (tools/native/ge007.u.linkmap.txt, produced by
    # tools/native/extract_linkmap.py from the matching build's map): the
    # same two dictionaries, already reduced to what this script consumes.
    # This is what the Windows build reads, so it needs no `make matching`.
    for ln in text.splitlines():
        if not ln or ln.startswith("#"):
            continue
        kind, name, val = ln.split()
        (seg if kind == "seg" else addr)[name] = int(val, 16)
else:
    # A raw linker map (build/u/ge007.u.map).
    for m in re.finditer(r"0x([0-9a-f]+)\s+(_\w+Segment(?:Rom)?(?:Start|End)) =", text):
        seg.setdefault(m.group(2), int(m.group(1), 16))
    for m in re.finditer(r"^\s+0x([0-9a-f]{8,16})\s+([A-Za-z_][A-Za-z0-9_]+)\s*$", text, re.M):
        addr.setdefault(m.group(2), int(m.group(1), 16))

unresolved = set(Path(unresolved_path).read_text().split())

lines = ['/* generated by gen_segments.py - do not edit */',
         '\t.section .note.GNU-stack,"",@progbits']
absn = 0
for name, val in sorted(seg.items()):
    if name.endswith("RomStart") or name.endswith("RomEnd"):
        lines.append(f"\t.globl {name}\n\t.set {name}, {val:#x}")
covered = set(n for n in seg if n.endswith(("RomStart", "RomEnd")))
done = set()
for name, val in sorted(seg.items()):
    if not name.endswith("SegmentStart") or name.endswith("RomStart"):
        continue
    base = name[:-len("Start")]
    end = base + "End"
    if end not in seg or base in done:
        continue
    done.add(base)
    size = seg[end] - val
    if size <= 0 or size > 0x800000:
        continue
    covered |= {name, end}
    lines.append(f"\t.bss\n\t.balign 16\n\t.globl {name}\n{name}:\n\t.space {size:#x}\n"
                 f"\t.globl {end}\n{end}:")
for name in sorted(unresolved):
    if name in covered or name not in addr:
        continue
    val = addr[name]
    if val < 0x04000000:
        lines.append(f"\t.globl {name}\n\t.set {name}, {val:#x}")
        absn += 1
        covered.add(name)
Path(out_path).write_text("\n".join(lines) + "\n")
Path(out_path + ".covered").write_text("\n".join(sorted(covered)) + "\n")
print(f"  absolutes from map: {absn}  segments: {len(done)}")
