#!/usr/bin/env python3
"""Generate the microcode DATA TABLE header from the locally extracted aspMain
data segment: the RESAMPLE polyphase coefficients and the ENVMIXER lane ramp.

(The file name is historical - it emitted only the resampler table first. Both
tables share one generated header because they share one source segment and one
extraction step; adding a second script would duplicate the fail-loud logic.)

The 64x4 Q15 polyphase table the RESAMPLE handler indexes lives in the
MICROCODE's own data segment, not in game data (POLEF's coefficients, by
contrast, arrive via LOADADPCM from the game's own banks). It is therefore
ROM-derived and follows the project's standing rule: extract locally, never
commit the bytes. bin/* is gitignored, and so is the generated header's home
under build/.

Fails loudly rather than silently emitting zeros - a silent zero table would
produce plausible-but-wrong audio, which is the one outcome worth preventing.
"""
import pathlib, struct, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC  = ROOT / "bin/aspboot.data.bin"
OUT  = ROOT / "build/native/sl_resample_tab.h"
OFF, N = 0xC0, 256           # 64 phases x 4 taps, Q15
RAMP_OFF, RAMP_N = 0xB0, 8   # ENVMIXER per-lane ramp, one per vector lane

def main() -> int:
    if not SRC.is_file():
        sys.stderr.write(
            f"gen_resample_tab: missing {SRC}\n"
            "  Run scripts/extract_asp_gsp_rsp.sh to extract the microcode\n"
            "  segments from your own ROM. Nothing ROM-derived is committed.\n")
        return 2
    d = SRC.read_bytes()
    if len(d) < RAMP_OFF + RAMP_N * 2:
        sys.stderr.write(f"gen_resample_tab: {SRC} too short for the ramp\n")
        return 2
    if len(d) < OFF + N * 2:
        sys.stderr.write(f"gen_resample_tab: {SRC} is too short "
                         f"({len(d)} bytes, need {OFF + N*2})\n")
        return 2
    v = struct.unpack(">%dh" % N, d[OFF:OFF + N * 2])
    ramp = struct.unpack(">%dh" % RAMP_N, d[RAMP_OFF:RAMP_OFF + RAMP_N * 2])
    if not any(ramp):
        sys.stderr.write("gen_resample_tab: the ENVMIXER ramp extracted as all "
                         "zeros - refusing to emit it. A zero ramp would make "
                         "every envelope construct to the same value, which is "
                         "plausible-looking and wrong.\n")
        return 2
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        f.write("/* GENERATED by tools/native/gen_resample_tab.py - do not "
                "commit. ROM-derived. */\n")
        f.write("#ifndef SL_RESAMPLE_TAB_H\n#define SL_RESAMPLE_TAB_H\n")
        f.write("#define SL_RESAMPLE_PHASES 64\n#define SL_RESAMPLE_TAPS 4\n")
        f.write("static const short SL_RESAMPLE_TAB[%d] = {\n" % N)
        for i in range(0, N, 8):
            f.write("  " + ",".join(str(x) for x in v[i:i + 8]) + ",\n")
        f.write("};\n")
        f.write("#define SL_ENVMIX_LANES %d\n" % RAMP_N)
        f.write("static const short SL_ENVMIX_RAMP[%d] = {\n  " % RAMP_N)
        f.write(",".join(str(x) for x in ramp))
        f.write("\n};\n#endif\n")
    print(f"gen_resample_tab: wrote {OUT} ({N} taps, {RAMP_N} ramp lanes)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
