/**
 * Native-only byte-swap for stage-setup propdef records (T4).
 *
 * Body generated by tools/native/gen_swap.py from the record structs
 * (regenerate with:
 *   tools/native/gen_swap.py src/bondtypes.h src/game/bondview.h <names>)
 * then hand-checked at the WARN spots: runtime_* fields and unions are
 * file-garbage overwritten before first read, so swapping them is inert;
 * byte-union members (keyID) are skipped correctly.
 *
 * The walk mirrors the loader: type at byte 3 (position is endian-neutral),
 * stride from sizepropdef().  Types without a generated struct get only
 * their header halfword swapped - their readers will surface them.
 */
#ifndef __sgi

#include <ultra64.h>
#include <bondgame.h>
#include "bondview.h"

extern s32 sizepropdef(PropDefHeaderRecord *pdef);

static u32 sl_ps32(u32 v)
{
    return (v >> 24) | ((v >> 8) & 0xFF00) | ((v << 8) & 0xFF0000) | (v << 24);
}

#define SW32(f) (*(u32 *) &(f) = sl_ps32(*(u32 *) &(f)))
#define SW16(f) (*(u16 *) &(f) = (u16) ((*(u16 *) &(f) >> 8) | (*(u16 *) &(f) << 8)))

/* THE INVARIANT: a per-type swapper may only write inside
 * [p, p + sizepropdef(p)).  The walk strides by sizepropdef(), so a swapper
 * that runs off the end of its own record scribbles on a record the walk has
 * not reached yet - and if it lands on that record's word 0, it rewrites the
 * type byte and the walk dispatches it to the wrong arm entirely.
 *
 * A struct is NOT a safe bound for this: bondtypes.h describes what the game
 * reads, and the game reads past the end of a camera record.  The file record
 * lengths are Action Block Types.txt's word-count table ("# of words for
 * type"), which sizepropdef() reproduces exactly for all 47 types.  Assert
 * each generated swapper's struct against that table, so a struct that grows
 * past its record fails the build instead of corrupting its neighbour. */
#define SL_STRIDE(tag, words) \
    typedef char sl_stride_##tag[(sizeof(struct tag) / 4 <= (words)) ? 1 : -1]

/* THE WORD-0 INVARIANT (sibling of the above): word 0 of every propdef record
 * IS the PropDefHeaderRecord - extrascale:u16, state:u8, type:u8 - and
 * sl_swap_PropDefHeaderRecord is its ONLY permitted writer.  Several structs
 * declare a u32 at offset 0 (objective_entry.id, setup_objective_text.unk00,
 * criteria_roomentered/deposit/picture.unk00); those are ALIASES of the
 * header, not fields, and SW32-ing one rotates the type byte out of byte 3.
 *
 * The game proves the aliasing itself: objective_status.c:179 walks
 *   for (objective = &objective_ptrs[n]->id; objective->type != ...;
 *        objective = sizepropdef(objective) + (PropDefHeaderRecord *)objective)
 * - it takes the address of `id` and reads `->type` and sizepropdef() through
 * it.  `id` is never read as a value anywhere: grep -rn -- '->id\b' src/game/
 * src/*.c returns exactly two hits, both in objective_status.c and both
 * address-of.  So not swapping it costs nothing and keeps the type byte.
 *
 * Why this is worse than a mis-strided swap walk: the swap walk is not the
 * only consumer.  prop.c:2004, loadobjectmodel.c:267/296/324/539,
 * cleanup_objects.c:81 and prop.c:68 all re-walk the SAME buffer with
 * sizepropdef().  A type byte destroyed here desynchronises every one of them,
 * which is why saving the stride before the switch (tried 2026-08-25, B-016)
 * repaired only this walk and left the crash exactly where it was. */

SL_STRIDE(GuardRecord, 7);                 /* 09 */
SL_STRIDE(DoorRecord, 0x40);               /* 01 */
SL_STRIDE(GlobalDoorScaleRecord, 2);       /* 02 */
SL_STRIDE(ObjectRecord, 0x20);             /* 03 05 0c 11 24 2a 2b - NOT 29,
                                            * which sizepropdef sizes at one
                                            * word; see the note in the walk */
SL_STRIDE(KeyRecord, 0x21);                /* 04 */
SL_STRIDE(AmmoCrateRecord, 0x21);          /* 07 */
SL_STRIDE(WeaponObjRecord, 0x22);          /* 08 */
SL_STRIDE(MonitorObjRecord, 0x40);         /* 0a */
SL_STRIDE(MultiMonitorObjRecord, 0x95);    /* 0b */
SL_STRIDE(AutogunRecord, 0x36);            /* 0d */
SL_STRIDE(MultiAmmoCrateRecord, 0x2d);     /* 14 */
SL_STRIDE(BodyArmourRecord, 0x22);         /* 15 */
SL_STRIDE(TagObjectRecord, 4);             /* 16 */
SL_STRIDE(objective_entry, 4);             /* 17 */
SL_STRIDE(criteria_picture, 4);            /* 1e */
SL_STRIDE(criteria_roomentered, 4);        /* 20 */
SL_STRIDE(criteria_deposit, 5);            /* 21 */
SL_STRIDE(watchMenuObjectiveText, 4);      /* 23 */
SL_STRIDE(RenameObjectRecord, 0xa);        /* 25 */
SL_STRIDE(VehichleRecord, 0x2c);           /* 27 */
SL_STRIDE(AircraftRecord, 0x2d);           /* 28 */
SL_STRIDE(TankRecord, 0x38);               /* 2d */
SL_STRIDE(CutsceneRecord, 7);              /* 2e */
SL_STRIDE(TintedGlassRecord, 0x25);        /* 2f */
/* 06 Camera is the one type where the struct is deliberately longer than the
 * record: 63 words declared against 0x3b in the file.  sl_swap_CCTVRecord
 * stops at unkE8 (word 58) for that reason - see the note there.  Pinning the
 * size makes a struct edit revisit that decision rather than silently move the
 * overhang. */
typedef char sl_stride_CCTVRecord[(sizeof(struct CCTVRecord) / 4 == 63) ? 1 : -1];

static void sl_swap_PropDefHeaderRecord(struct PropDefHeaderRecord *r)
{
    SW16(r->extrascale);
}

static void sl_swap_GuardRecord(struct GuardRecord *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW16(r->chrnum);
    SW16(r->PadID);
    SW16(r->BodyID);
    SW16(r->AIListID);
    SW16(r->Preset);
    SW16(r->chrpreset1);
    SW16(r->health);
    SW16(r->ReactionTime);
    SW16(r->bitflags);
    SW16(r->HeadID);
    SW32(r->Data);
}

static void sl_swap_ObjectRecord(struct ObjectRecord *r)
{
    s32 i;

    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW16(r->obj);
    SW16(r->pad);
    SW32(r->flags);
    SW32(r->flags2);
    /* runtime slots hold file garbage the N64 absorbs by chasing pointers
     * through its everything-readable TLB; natively they get the honest
     * initial state instead */
    r->prop = NULL;
    r->model = NULL;
    for (i = 0; i < 16; i++) ((u32 *) &r->mtx)[i] = 0;
    for (i = 0; i < 3; i++) ((u32 *) &r->runtime_pos)[i] = 0;
    r->runtime_bitflags = 0;
    r->ptr_allocated_collisiondata_block = NULL;
    r->projectile = NULL;
    SW32(r->maxdamage);
    SW32(r->damage);
}

static void sl_swap_ModelRoData_BoundingBoxRecord(struct ModelRoData_BoundingBoxRecord *r)
{
    s32 i;

    SW32(r->ModelNumber);
    for (i = 0; i < 6; i++) SW32(((u32 *) &r->Bounds)[i]);
}

static void sl_swap_DoorRecord(struct DoorRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->linkedDoorOffset);
    SW32(r->maxFrac);
    SW32(r->perimFrac);
    SW32(r->accel);
    SW32(r->decel);
    SW32(r->maxSpeed);
    SW16(r->doorFlags);
    SW16(r->doorType);
    SW32(r->keyflags);
    SW32(r->autoCloseFrames);
    SW32(r->doorOpenSound);
    SW32(r->frac);
    SW32(r->unkac);
    SW32(r->unkb0);
    SW32(r->openPosition);
    SW32(r->speed);
    SW16(r->calculatedopacity);
    SW32(r->TintDist);
    SW16(r->CullDist);
    SW32(r->linkedDoor);
    SW32(r->unkcc);
    sl_swap_ModelRoData_BoundingBoxRecord(&r->bbox);
    SW32(r->openedTime);
    SW32(r->portalNumber);
    SW32(r->openSoundState);
    SW32(r->closeSoundState);
    SW32(r->lastcalc60i);                                     /* runtime, inert at load */
}

static void sl_swap_GlobalDoorScaleRecord(struct GlobalDoorScaleRecord *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW32(r->Scale);
}

static void sl_swap_WeaponObjRecord(struct WeaponObjRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW16(r->timer);
    SW32(r->dualweapon);
}

static void sl_swap_KeyRecord(struct KeyRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    /* B-033.  The word at 0x80 is a UNION, and the generator resolved it the
     * wrong way: it saw `s8 keyID` first and skipped the word as a byte field.
     * The file's own authority says otherwise - "object block types.txt", type
     * 04 key, annotates offset 0x80 as "lock bit values.  Door locks are masked
     * with these values in order to open them", and its example holds the
     * 32-bit word 00 00 00 06.  bondinv.c:744 is the reader that matters
     * (heldkeyflags |= key->keyflags), and it ANDs the result against
     * DoorRecord.keyflags, which sl_swap_DoorRecord DOES SW32 - so leaving this
     * one unswapped made every locked door unopenable natively.
     *
     * Word 0x80 is the last word of a 0x21-word record, so this stays inside
     * the record.  keyID survives as the wire word's MSB; its one reader
     * (propobj.c check_if_entry_is_collectable) extracts it arithmetically. */
    SW32(r->keyflags);
}

static void sl_swap_CCTVRecord(struct CCTVRecord *r)
{
    s32 i;

    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->lookpad);
    for (i = 0; i < 16; i++) SW32(((u32 *) &r->unk84)[i]);
    SW32(r->unkC4);
    SW32(r->unkC8);
    SW32(r->unkCC);
    SW32(r->unkD0);
    SW32(r->unkD4);
    SW32(r->unkD8);
    SW32(r->unkDC);
    SW32(r->timer);
    SW32(r->convert_to_f32);
    SW32(r->unkE8);
    /* STOP.  The file record is 0x3b words (Action Block Types.txt: "06 3B
     * Camera"), which is what sizepropdef() returns and therefore what the
     * walk below strides by - but sizeof(CCTVRecord) is 63 words.  unkEC,
     * unkF0, unkF4 and unkF8 are the four-word overhang: they are declared by
     * the struct and are NOT in the file.  Swapping them writes into the NEXT
     * record.  Measured on surface: the camera at 0xf5d2c568 overhangs onto
     * the type-5 ALARM at 0xf5d2c654, and SW32 of its header word 01 00 00 05
     * lands 05 00 00 01, turning type 5 into type 1.  The walk then dispatched
     * it to the Door arm, whose SW16(obj)/SW16(pad) on already-word-swapped
     * bytes transposed the pair - and setupDoor called modelLoad(25127) with
     * pad's tag.
     *
     * Every camera in every level did this; only the victim's first wire byte
     * decided whether it crashed.  Counted across the wire data: surface has 1
     * camera and it lands on an ALARM whose byte 0 is 0x01, so type 5 became
     * type 1; surface2 has 4 (last one lands on a PROP -> DOOR); bunker2 has 6
     * (last one lands on an AUTOGUN -> DOOR).  Those are exactly the three
     * levels that segfaulted.  The other victims are TAG records whose byte 0
     * is 0x00, so type 22 became type 0 - a 1-word stride that desynchronised
     * the rest of the walk silently instead of loudly.  facility and dam have
     * no cameras at all, which is why 14 levels booted regardless.
     *
     * Grepped tree-wide: unkEC/unkF0/unkF4/unkF8 appear only in bondtypes.h
     * and here, so nothing in src/ ever reads them.  The N64 reads whatever
     * follows and absorbs it; we must not WRITE it. */
}

static void sl_swap_AutogunRecord(struct AutogunRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->padID);
    SW32(r->rot_related);
    SW32(r->unk88);
    SW32(r->unk8C);
    SW32(r->unk90);
    SW32(r->unk94);
    SW32(r->unk98);
    SW32(r->unk9C);
    SW32(r->unkA0);
    SW32(r->speed);
    SW32(r->aimdist);
    SW32(r->unkAC);
    SW32(r->unkB0);
    SW32(r->unkB4);
    SW32(r->unkB8);
    SW32(r->unkBC);
    SW32(r->unkC0);
    SW32(r->unkC4);
    SW32(r->unkC8);
    SW32(r->beam);
    SW32(r->is_active);
    SW32(r->unkD4);
}

static void sl_swap_MonitorRecord(struct MonitorRecord *r)
{
    SW32(r->cmdlist);
    SW16(r->offset);
    SW16(r->pause60);
    SW32(r->tconfig);
    SW32(r->rot);
    SW32(r->xscale);
    SW32(r->xscalefrac);
    SW32(r->xscaleinc);
    SW32(r->xscaleold);
    SW32(r->xscalenew);
    SW32(r->yscale);
    SW32(r->yscalefrac);
    SW32(r->yscaleinc);
    SW32(r->yscaleold);
    SW32(r->yscalenew);
    SW32(r->xmid);
    SW32(r->xmidfrac);
    SW32(r->xmidinc);
    SW32(r->xmidold);
    SW32(r->xmidnew);
    SW32(r->ymid);
    SW32(r->ymidfrac);
    SW32(r->ymidinc);
    SW32(r->ymidold);
    SW32(r->ymidnew);
    SW32(r->colfrac);
    SW32(r->colinc);
}

static void sl_swap_MonitorObjRecord(struct MonitorObjRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    sl_swap_MonitorRecord(&r->Monitor);
    SW32(r->OwnerOffset);
    SW32(r->OwnerPart);
    SW32(r->ImageNum);
}

static void sl_swap_MultiMonitorObjRecord(struct MultiMonitorObjRecord *r)
{
    s32 i;

    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    for (i = 0; i < 4; i++) sl_swap_MonitorRecord(&r->Monitor[i]);
}

static void sl_swap_BodyArmourRecord(struct BodyArmourRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->initialamount);
    SW32(r->amount);
}

static void sl_swap_TintedGlassRecord(struct TintedGlassRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->TintDist);
    SW32(r->CullDist);
    SW32(r->calculatedopacity);
    SW32(r->portalnum);
    SW32(r->unk90);
}

static void sl_swap_multiammocrateslot(struct multiammocrateslot *r)
{
    SW16(r->modelnum);
    SW16(r->quantity);
}

static void sl_swap_MultiAmmoCrateRecord(struct MultiAmmoCrateRecord *r)
{
    s32 i;

    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    for (i = 0; i < AMMOTYPE_GLOBAL_MAX; i++) sl_swap_multiammocrateslot(&r->slots[i]);
}

static void sl_swap_TankRecord(struct TankRecord *r)
{
    s32 i;

    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->collision);
    for (i = 0; i < 8; i++) SW32(((u32 *) &r->rect)[i]);
    SW32(r->unkA4);
    SW32(r->unkA8);
    SW32(r->unkAC);
    SW32(r->unkB0);
    SW32(r->unkB4);
    SW32(r->unkB8);
    SW32(r->unkBC);
    SW32(r->unkC0);
    SW32(r->is_firing_tank);
    SW32(r->turret_vertical_angle);
    SW32(r->turret_orientation_angle);
    SW32(r->unkD0);
    SW32(r->stan_y);
    SW32(r->unkD8);
    SW32(r->tank_orientation_angle);
}

static void sl_swap_VehichleRecord(struct VehichleRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->ailist);
    SW16(r->aioffset);
    SW16(r->aireturnlist);
    SW32(r->speed);
    SW32(r->wheelxrot);
    SW32(r->wheelyrot);
    SW32(r->speedaim);
    SW32(r->speedtime60);
    SW32(r->turnrot60);
    SW32(r->roty);
    SW32(r->path);
    SW32(r->nextstep);
    SW32(r->Sound);
}

static void sl_swap_AircraftRecord(struct AircraftRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->ailist);
    SW16(r->aioffset);
    SW16(r->aireturnlist);
    SW32(r->rotoryrot);
    SW32(r->rotaryspeed);
    SW32(r->rotaryspeedaim);
    SW32(r->rotaryspeedtime);
    SW32(r->speed);
    SW32(r->speedaim);
    SW32(r->speedtime60);
    SW32(r->yrot);
    SW32(r->nextstep);
    SW32(r->path);
    SW32(r->Sound);
}

static void sl_swap_TagObjectRecord(struct TagObjectRecord *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW16(r->ID);
    SW16(r->OffsetToObj);
    SW32(r->NextTag);
    SW32(r->TaggedObject);
}

static void sl_swap_RenameObjectRecord(struct RenameObjectRecord *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW32(r->TagID);
    SW32(r->unk08);
    SW32(r->unk0c);
    SW32(r->unk10);
    SW32(r->unk14);
    SW32(r->unk18);
    SW32(r->unk1c);
    SW32(r->unk20);
    SW32(r->renobj);
}

static void sl_swap_textoverride(struct textoverride *r)
{
    SW32(r->unk1);
    SW32(r->objoffset);
    SW32(r->weapon);
    SW32(r->titletext1);
    SW32(r->titletext2);
    SW32(r->shorttext);
    SW32(r->longtext);
    SW32(r->pickuptext);
    SW32(r->next);
    SW32(r->obj);
}

static void sl_swap_CutsceneRecord(struct CutsceneRecord *r)
{
    s32 i;

    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    for (i = 0; i < 3; i++) SW32(((u32 *) &r->pos)[i]);
    SW32(r->theta);
    SW32(r->verta);
    SW32(r->pad);
}

static void sl_swap_objective_entry(struct objective_entry *r)
{
    /* r->id is word 0 - it IS the header, not a field.  See THE WORD-0
     * INVARIANT above; sl_swap_PropDefHeaderRecord is the only writer. */
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW32(r->menu);
    /* WARN assumed 32-bit enum/typedef: WATCH_BRIEFING_PAGE menu */
    SW16(r->reserved);
    SW16(r->text);
    SW16(r->unkC);
}

static void sl_swap_criteria_roomentered(struct criteria_roomentered *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW32(r->pad);
    SW32(r->status);
    SW32(r->next);
}

static void sl_swap_criteria_deposit(struct criteria_deposit *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW32(r->weaponnum);
    SW32(r->padid);
    SW32(r->flag);
    SW32(r->next);
}

static void sl_swap_criteria_picture(struct criteria_picture *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW32(r->tag_id);
    SW32(r->flag);
    SW32(r->next);
}

/* Type 23, the watch briefing text.  Word 2 is TWO halfwords, not one word.
 *
 * "7F057104 - return watch text for briefing A0.txt" gives the record as
 *
 *     00000023 0000000x 0000tttt rrrrrrrr
 *     x  menu option to fill      t  text to display
 *     r  RESERVED for pointer to next entry at runtime
 *
 * and the disassembly there reads the ID with `LHU A0,000A (V0)` - a HALFWORD
 * at offset 0x0A - after `LW T6,0004 (V0)` for the menu and `LW V0,000C (V0)`
 * for the next pointer.  That is exactly struct watchMenuObjectiveText, so the
 * swap is written against that rather than the opaque setup_objective_text
 * whose unk08 spans both halves.
 *
 * SW32 over word 2 byte-reverses all four bytes, which does not merely
 * mis-order the ID - it moves it.  MEASURED on facility before this change,
 * every one of the five records:
 *
 *     raw[0x08] = 2b 0c 00 00  ->  reserved=0c2b  text=0000
 *     langGet(text=0000)     = NULL
 *     langGet(reserved=0c2b) = "A R K A N G E L S K"
 *
 * langGet(0) returning NULL is what made get_ptr_text_for_watch_breifing_page
 * fall through to Rare's own "E R R O R\n" default for page 0, which is the
 * stage LOCATION line at the top of the watch briefing pages.  The other four
 * records resolved to the overview, M, Q and Moneypenny texts through the same
 * displaced field, which is the control proving the language tables were
 * loaded and the ID was simply wrong.  The fallback is Rare's and stays; what
 * is fixed is the lookup that should never have failed.
 *
 * The sibling at type 17 (sl_swap_objective_entry) already spells this pair as
 * two SW16s, which is why the objective LIST rendered while its header did
 * not. */
static void sl_swap_watchMenuObjectiveText(struct watchMenuObjectiveText *r)
{
    sl_swap_PropDefHeaderRecord((struct PropDefHeaderRecord *) r);
    SW32(r->menu);
    SW16(r->reserved);
    SW16(r->text);
    SW32(r->nextentry);
}


static void sl_swap_AmmoCrateRecord(struct AmmoCrateRecord *r)
{
    sl_swap_ObjectRecord((struct ObjectRecord *) r);
    SW32(r->ammoType);
}

void sl_propdefs_swap(void *propDefs)
{
    PropDefHeaderRecord *p = propDefs;

    while (p->type != PROPDEF_END) {
        switch (p->type) {
            case PROPDEF_GUARD:          sl_swap_GuardRecord((struct GuardRecord *) p); break;
            case PROPDEF_DOOR:           sl_swap_DoorRecord((struct DoorRecord *) p); break;
            case PROPDEF_DOOR_SCALE:     sl_swap_GlobalDoorScaleRecord((struct GlobalDoorScaleRecord *) p); break;
            case PROPDEF_COLLECTABLE:    sl_swap_WeaponObjRecord((struct WeaponObjRecord *) p); break;
            case PROPDEF_KEY:            sl_swap_KeyRecord((struct KeyRecord *) p); break;
            case PROPDEF_CCTV:           sl_swap_CCTVRecord((struct CCTVRecord *) p); break;
            case PROPDEF_AUTOGUN:        sl_swap_AutogunRecord((struct AutogunRecord *) p); break;
            case PROPDEF_MONITOR:        sl_swap_MonitorObjRecord((struct MonitorObjRecord *) p); break;
            case PROPDEF_MULTI_MONITOR:  sl_swap_MultiMonitorObjRecord((struct MultiMonitorObjRecord *) p); break;
            case PROPDEF_ARMOUR:         sl_swap_BodyArmourRecord((struct BodyArmourRecord *) p); break;
            case PROPDEF_TINTED_GLASS:   sl_swap_TintedGlassRecord((struct TintedGlassRecord *) p); break;
            case PROPDEF_AMMO:           sl_swap_MultiAmmoCrateRecord((struct MultiAmmoCrateRecord *) p); break;
            case PROPDEF_TANK:           sl_swap_TankRecord((struct TankRecord *) p); break;
            case PROPDEF_VEHICHLE:       sl_swap_VehichleRecord((struct VehichleRecord *) p); break;
            case PROPDEF_AIRCRAFT:       sl_swap_AircraftRecord((struct AircraftRecord *) p); break;
            case PROPDEF_TAG:            sl_swap_TagObjectRecord((struct TagObjectRecord *) p); break;
            case PROPDEF_RENAME:         sl_swap_RenameObjectRecord((struct RenameObjectRecord *) p); break;
            case PROPDEF_CAMERAPOS:      sl_swap_CutsceneRecord((struct CutsceneRecord *) p); break;
            case PROPDEF_OBJECTIVE_START: sl_swap_objective_entry((struct objective_entry *) p); break;
            case PROPDEF_OBJECTIVE_ENTER_ROOM: sl_swap_criteria_roomentered((struct criteria_roomentered *) p); break;
            case PROPDEF_OBJECTIVE_DEPOSIT_OBJECT_IN_ROOM: sl_swap_criteria_deposit((struct criteria_deposit *) p); break;
            case PROPDEF_OBJECTIVE_PHOTOGRAPH: sl_swap_criteria_picture((struct criteria_picture *) p); break;
            case PROPDEF_WATCH_MENU_OBJECTIVE_TEXT: sl_swap_watchMenuObjectiveText((struct watchMenuObjectiveText *) p); break;
            case PROPDEF_MAGAZINE:
                sl_swap_AmmoCrateRecord((struct AmmoCrateRecord *) p);
                break;
            case PROPDEF_PROP:
            case PROPDEF_ALARM:
            case PROPDEF_GLASS:
            case PROPDEF_SAFE:
            case PROPDEF_HAT:
            case PROPDEF_RACK:
            /* GAS_RELEASING and UNK41 belong here because prop.c consumes them
             * here: its case block casts PROP, ALARM, MAGAZINE, GAS_RELEASING,
             * UNK41, GLASS and SAFE alike to ObjectRecord and hands each to
             * domakedefaultobj.  Left in the default arm they were swept as
             * whole words, and word 1 of an ObjectRecord is not one word - it
             * is the two s16 fields obj and pad.  Swapping that pair as a u32
             * transposes them, so Facility's gas tanks reached modelLoad with
             * obj holding pad's tag (10000) instead of their model (117), and
             * PitemZ_entries[10000].header was NULL.  Measured, not inferred:
             * wire bytes 00 75 27 10 swept as a word land as 10 27 75 00,
             * which reads back exactly as obj=0x2710 pad=0x0075. */
            case PROPDEF_GAS_RELEASING:
                sl_swap_ObjectRecord((struct ObjectRecord *) p);
                break;
            /* PROPDEF_UNK41 (0x29) belongs with them by how prop.c CONSUMES it
             * - the same case block casts it to ObjectRecord - and it was put
             * here for that reason in ac34de10. That was wrong, and it is THE
             * INVARIANT above being broken by the commit that documented it.
             *
             * sizepropdef has no case for 0x29 (loadobjectmodel.c:47-146), so
             * it falls to the default arm and returns
             * sizeof(PropDefHeaderRecord)/4 = ONE word. sl_swap_ObjectRecord
             * writes 32. That is a 31-word overrun into records the walk has
             * not reached yet - exactly the fault that made a camera rewrite
             * its neighbour's type byte and cost three levels.
             *
             * GAS_RELEASING above is genuinely different: sizepropdef DOES
             * case it, at sizeof(ObjectRecord)/4, so 32 words is its stride.
             *
             * Rare reading past a short record is Rare's business and rule 5
             * leaves it alone; this file may not WRITE there. Falling through
             * to the default arm swaps the header halfword and sweeps
             * stride-1 = 0 further words, which is the whole of what 0x29
             * owns.
             *
             * Never fired: zero 0x29 records across all 20 campaign levels'
             * walks. It would fire on multiplayer or custom setups. */
            default:
            {
                /* the remaining types (SAFE_ITEM, LOCK_DOOR, LINK, SWITCH,
                 * GUARD_ATTRIBUTE, the objective payloads) are all a header
                 * plus s32 index/argument words - the linking passes read
                 * them as whole words.  Sweep words 1..stride-1. */
                s32 sl_n = sizepropdef(p);
                s32 sl_i;
                u32 *sl_w = (u32 *) p;

                SW16(p->extrascale);
                for (sl_i = 1; sl_i < sl_n; sl_i++)
                    SW32(sl_w[sl_i]);
                break;
            }
        }
        /* Safe to re-read the type here only because of THE WORD-0 INVARIANT:
         * no swapper above may touch bytes 2-3 of word 0. */
        p = (PropDefHeaderRecord *) ((u32 *) p + sizepropdef(p));
    }
}

#endif /* !__sgi */
