ItemModelFileRecord PitemZ_entries[] = {
    #include <assets/obseg/prop/alarm1/propFileRecord.inc.c>
    #include <assets/obseg/prop/alarm2/propFileRecord.inc.c>
    #include <assets/obseg/prop/explosionbit/propFileRecord.inc.c>
    #include <assets/obseg/prop/ammo_crate1/propFileRecord.inc.c>
    #include <assets/obseg/prop/ammo_crate2/propFileRecord.inc.c>
    #include <assets/obseg/prop/ammo_crate3/propFileRecord.inc.c>
    #include <assets/obseg/prop/ammo_crate4/propFileRecord.inc.c>
    #include <assets/obseg/prop/ammo_crate5/propFileRecord.inc.c>
    #include <assets/obseg/prop/bin1/propFileRecord.inc.c>
    #include <assets/obseg/prop/blotter1/propFileRecord.inc.c>
    #include <assets/obseg/prop/book1/propFileRecord.inc.c>
    #include <assets/obseg/prop/bookshelf1/propFileRecord.inc.c>
    #include <assets/obseg/prop/bridge_console1a/propFileRecord.inc.c>
    #include <assets/obseg/prop/bridge_console1b/propFileRecord.inc.c>
    #include <assets/obseg/prop/bridge_console2a/propFileRecord.inc.c>
    #include <assets/obseg/prop/bridge_console2b/propFileRecord.inc.c>
    #include <assets/obseg/prop/bridge_console3a/propFileRecord.inc.c>
    #include <assets/obseg/prop/bridge_console3b/propFileRecord.inc.c>
    #include <assets/obseg/prop/card_box1/propFileRecord.inc.c>
    #include <assets/obseg/prop/card_box2/propFileRecord.inc.c>
    #include <assets/obseg/prop/card_box3/propFileRecord.inc.c>
    #include <assets/obseg/prop/card_box4_lg/propFileRecord.inc.c>
    #include <assets/obseg/prop/card_box5_lg/propFileRecord.inc.c>
    #include <assets/obseg/prop/card_box6_lg/propFileRecord.inc.c>
    #include <assets/obseg/prop/cctv/propFileRecord.inc.c>
    #include <assets/obseg/prop/console1/propFileRecord.inc.c>
    #include <assets/obseg/prop/console2/propFileRecord.inc.c>
    #include <assets/obseg/prop/console3/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_seva/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sevb/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sevc/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sevd/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sev2a/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sev2b/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sev2c/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sev2d/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sev_GEa/propFileRecord.inc.c>
    #include <assets/obseg/prop/console_sev_GEb/propFileRecord.inc.c>
    #include <assets/obseg/prop/desk1/propFileRecord.inc.c>
    #include <assets/obseg/prop/desk2/propFileRecord.inc.c>
    #include <assets/obseg/prop/desk_lamp2/propFileRecord.inc.c>
    #include <assets/obseg/prop/disc_reader/propFileRecord.inc.c>
    #include <assets/obseg/prop/disk_drive1/propFileRecord.inc.c>
    #include <assets/obseg/prop/filing_cabinet1/propFileRecord.inc.c>
    #include <assets/obseg/prop/jerry_can1/propFileRecord.inc.c>
    #include <assets/obseg/prop/keyboard1/propFileRecord.inc.c>
    #include <assets/obseg/prop/kit_units1/propFileRecord.inc.c>
    #include <assets/obseg/prop/letter_tray1/propFileRecord.inc.c>
    #include <assets/obseg/prop/mainframe1/propFileRecord.inc.c>
    #include <assets/obseg/prop/mainframe2/propFileRecord.inc.c>
    #include <assets/obseg/prop/metal_chair1/propFileRecord.inc.c>
    #include <assets/obseg/prop/metal_crate1/propFileRecord.inc.c>
    #include <assets/obseg/prop/metal_crate2/propFileRecord.inc.c>
    #include <assets/obseg/prop/metal_crate3/propFileRecord.inc.c>
    #include <assets/obseg/prop/metal_crate4/propFileRecord.inc.c>
    #include <assets/obseg/prop/missile_rack/propFileRecord.inc.c>
    #include <assets/obseg/prop/missile_rack2/propFileRecord.inc.c>
    #include <assets/obseg/prop/oil_drum1/propFileRecord.inc.c>
    #include <assets/obseg/prop/oil_drum2/propFileRecord.inc.c>
    #include <assets/obseg/prop/oil_drum3/propFileRecord.inc.c>
    #include <assets/obseg/prop/oil_drum5/propFileRecord.inc.c>
    #include <assets/obseg/prop/oil_drum6/propFileRecord.inc.c>
    #include <assets/obseg/prop/oil_drum7/propFileRecord.inc.c>
    #include <assets/obseg/prop/padlock/propFileRecord.inc.c>
    #include <assets/obseg/prop/phone1/propFileRecord.inc.c>
    #include <assets/obseg/prop/radio_unit1/propFileRecord.inc.c>
    #include <assets/obseg/prop/radio_unit2/propFileRecord.inc.c>
    #include <assets/obseg/prop/radio_unit3/propFileRecord.inc.c>
    #include <assets/obseg/prop/radio_unit4/propFileRecord.inc.c>
    #include <assets/obseg/prop/sat1_reflect/propFileRecord.inc.c>
    #include <assets/obseg/prop/satdish/propFileRecord.inc.c>
    #include <assets/obseg/prop/satbox/propFileRecord.inc.c>
    #include <assets/obseg/prop/stool1/propFileRecord.inc.c>
    #include <assets/obseg/prop/swivel_chair1/propFileRecord.inc.c>
    #include <assets/obseg/prop/torpedo_rack/propFileRecord.inc.c>
    #include <assets/obseg/prop/tv1/propFileRecord.inc.c>
    #include <assets/obseg/prop/tv_holder/propFileRecord.inc.c>
    #include <assets/obseg/prop/tvscreen/propFileRecord.inc.c>
    #include <assets/obseg/prop/tv4screen/propFileRecord.inc.c>
    #include <assets/obseg/prop/wood_lg_crate1/propFileRecord.inc.c>
    #include <assets/obseg/prop/wood_lg_crate2/propFileRecord.inc.c>
    #include <assets/obseg/prop/wood_md_crate3/propFileRecord.inc.c>
    #include <assets/obseg/prop/wood_sm_crate4/propFileRecord.inc.c>
    #include <assets/obseg/prop/wood_sm_crate5/propFileRecord.inc.c>
    #include <assets/obseg/prop/wood_sm_crate6/propFileRecord.inc.c>
    #include <assets/obseg/prop/wooden_table1/propFileRecord.inc.c>
    #include <assets/obseg/prop/swipe_card2/propFileRecord.inc.c>
    #include <assets/obseg/prop/borg_crate/propFileRecord.inc.c>
    #include <assets/obseg/prop/boxes4x4/propFileRecord.inc.c>
    #include <assets/obseg/prop/boxes3x4/propFileRecord.inc.c>
    #include <assets/obseg/prop/boxes2x4/propFileRecord.inc.c>
    #include <assets/obseg/prop/sec_panel/propFileRecord.inc.c>
    #include <assets/obseg/prop/ICBM_nose/propFileRecord.inc.c>
    #include <assets/obseg/prop/ICBM/propFileRecord.inc.c>
    #include <assets/obseg/prop/tuning_console1/propFileRecord.inc.c>
    #include <assets/obseg/prop/desk_arecibo1/propFileRecord.inc.c>
    #include <assets/obseg/prop/locker3/propFileRecord.inc.c>
    #include <assets/obseg/prop/locker4/propFileRecord.inc.c>
    #include <assets/obseg/prop/roofgun/propFileRecord.inc.c>
    #include <assets/obseg/prop/dest_engine/propFileRecord.inc.c>
    #include <assets/obseg/prop/dest_exocet/propFileRecord.inc.c>
    #include <assets/obseg/prop/dest_gun/propFileRecord.inc.c>
    #include <assets/obseg/prop/dest_harpoon/propFileRecord.inc.c>
    #include <assets/obseg/prop/dest_seawolf/propFileRecord.inc.c>
    #include <assets/obseg/prop/window/propFileRecord.inc.c>
    #include <assets/obseg/prop/window_lib_lg1/propFileRecord.inc.c>
    #include <assets/obseg/prop/window_lib_sm1/propFileRecord.inc.c>
    #include <assets/obseg/prop/window_cor11/propFileRecord.inc.c>
    #include <assets/obseg/prop/jungle3_tree/propFileRecord.inc.c>
    #include <assets/obseg/prop/palm/propFileRecord.inc.c>
    #include <assets/obseg/prop/palmtree/propFileRecord.inc.c>
    #include <assets/obseg/prop/plant2b/propFileRecord.inc.c>
    #include <assets/obseg/prop/labbench/propFileRecord.inc.c>
    #include <assets/obseg/prop/gasbarrel/propFileRecord.inc.c>
    #include <assets/obseg/prop/gasbarrels/propFileRecord.inc.c>
    #include <assets/obseg/prop/bodyarmour/propFileRecord.inc.c>
    #include <assets/obseg/prop/bodyarmourvest/propFileRecord.inc.c>
    #include <assets/obseg/prop/gastank/propFileRecord.inc.c>
    #include <assets/obseg/prop/glassware1/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatchbolt/propFileRecord.inc.c>
    #include <assets/obseg/prop/brakeunit/propFileRecord.inc.c>
    #include <assets/obseg/prop/ak47mag/propFileRecord.inc.c>
    #include <assets/obseg/prop/m16mag/propFileRecord.inc.c>
    #include <assets/obseg/prop/mp5kmag/propFileRecord.inc.c>
    #include <assets/obseg/prop/skorpionmag/propFileRecord.inc.c>
    #include <assets/obseg/prop/spectremag/propFileRecord.inc.c>
    #include <assets/obseg/prop/uzimag/propFileRecord.inc.c>
    #include <assets/obseg/prop/silencer/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrextinguisher/propFileRecord.inc.c>
    #include <assets/obseg/prop/boxcartridges/propFileRecord.inc.c>
    #include <assets/obseg/prop/fnp90mag/propFileRecord.inc.c>
    #include <assets/obseg/prop/goldenshells/propFileRecord.inc.c>
    #include <assets/obseg/prop/magnumshells/propFileRecord.inc.c>
    #include <assets/obseg/prop/wppkmag/propFileRecord.inc.c>
    #include <assets/obseg/prop/tt33mag/propFileRecord.inc.c>
    #include <assets/obseg/prop/sev_door/propFileRecord.inc.c>
    #include <assets/obseg/prop/sev_door3/propFileRecord.inc.c>
    #include <assets/obseg/prop/sev_door3_wind/propFileRecord.inc.c>
    #include <assets/obseg/prop/sev_door4_wind/propFileRecord.inc.c>
    #include <assets/obseg/prop/sev_trislide/propFileRecord.inc.c>
    #include <assets/obseg/prop/sev_door_v1/propFileRecord.inc.c>
    #include <assets/obseg/prop/steel_door1/propFileRecord.inc.c>
    #include <assets/obseg/prop/steel_door2/propFileRecord.inc.c>
    #include <assets/obseg/prop/steel_door3/propFileRecord.inc.c>
    #include <assets/obseg/prop/silo_lift_door/propFileRecord.inc.c>
    #include <assets/obseg/prop/steel_door2b/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_roller1/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_roller2/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_roller3/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_roller4/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_st_arec1/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_st_arec2/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_dest1/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_dest2/propFileRecord.inc.c>
    #include <assets/obseg/prop/gas_plant_sw_do1/propFileRecord.inc.c>
    #include <assets/obseg/prop/gas_plant_sw2_do1/propFileRecord.inc.c>
    #include <assets/obseg/prop/gas_plant_sw3_do1/propFileRecord.inc.c>
    #include <assets/obseg/prop/gas_plant_sw4_do1/propFileRecord.inc.c>
    #include <assets/obseg/prop/gas_plant_met1_do1/propFileRecord.inc.c>
    #include <assets/obseg/prop/gas_plant_wc_cub1/propFileRecord.inc.c>
    #include <assets/obseg/prop/gasplant_clear_door/propFileRecord.inc.c>
    #include <assets/obseg/prop/train_door/propFileRecord.inc.c>
    #include <assets/obseg/prop/train_door2/propFileRecord.inc.c>
    #include <assets/obseg/prop/train_door3/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_eyelid/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_iris/propFileRecord.inc.c>
    #include <assets/obseg/prop/sevdoorwood/propFileRecord.inc.c>
    #include <assets/obseg/prop/sevdoorwind/propFileRecord.inc.c>
    #include <assets/obseg/prop/sevdoornowind/propFileRecord.inc.c>
    #include <assets/obseg/prop/sevdoormetslide/propFileRecord.inc.c>
    #include <assets/obseg/prop/cryptdoor1a/propFileRecord.inc.c>
    #include <assets/obseg/prop/cryptdoor1b/propFileRecord.inc.c>
    #include <assets/obseg/prop/cryptdoor2a/propFileRecord.inc.c>
    #include <assets/obseg/prop/cryptdoor2b/propFileRecord.inc.c>
    #include <assets/obseg/prop/cryptdoor3/propFileRecord.inc.c>
    #include <assets/obseg/prop/cryptdoor4/propFileRecord.inc.c>
    #include <assets/obseg/prop/vertdoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatchdoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/damgatedoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/damtundoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/damchaindoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/silotopdoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/doorprison1/propFileRecord.inc.c>
    #include <assets/obseg/prop/doorstatgate/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrkalash/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgrenadelaunch/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrknife/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrlaser/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrm16/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrmp5k/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrruger/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrwppk/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrshotgun/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrskorpion/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrspectre/propFileRecord.inc.c>
    #include <assets/obseg/prop/chruzi/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgrenade/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrfnp90/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrbriefcase/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrremotemine/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrproximitymine/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrtimedmine/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrrocket/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgrenaderound/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrwppksil/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrtt33/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrmp5ksil/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrautoshot/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgolden/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrthrowknife/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrsniperrifle/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrrocketlaunch/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatfurry/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatfurrybrown/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatfurryblack/propFileRecord.inc.c>
    #include <assets/obseg/prop/hattbird/propFileRecord.inc.c>
    #include <assets/obseg/prop/hattbirdbrown/propFileRecord.inc.c>
    #include <assets/obseg/prop/hathelmet/propFileRecord.inc.c>
    #include <assets/obseg/prop/hathelmetgrey/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatmoon/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatberet/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatberetblue/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatberetred/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatpeaked/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrwristdart/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrexplosivepen/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrbombcase/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrflarepistol/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrpitongun/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrfingergun/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrsilverwppk/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgoldwppk/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrdynamite/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrbungee/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrdoordecoder/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrbombdefuser/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrbugdetector/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrsafecrackercase/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrcamera/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrlockexploder/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrdoorexploder/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrkeyanalysercase/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrweaponcase/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrkeyyale/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrkeybolt/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrbug/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrmicrocamera/propFileRecord.inc.c>
    #include <assets/obseg/prop/floppy/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgoldeneyekey/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrpolarizedglasses/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrcreditcard/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrdarkglasses/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgaskeyring/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrdatathief/propFileRecord.inc.c>
    #include <assets/obseg/prop/safe/propFileRecord.inc.c>
    #include <assets/obseg/prop/bomb/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrplans/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrspyfile/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrblueprints/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrcircuitboard/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrmap/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrspooltape/propFileRecord.inc.c>
    #include <assets/obseg/prop/chraudiotape/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrmicrofilm/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrmicrocode/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrlectre/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrmoney/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrgoldbar/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrheroin/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrclipboard/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrdossierred/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrstafflist/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrdattape/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrplastique/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrblackbox/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrvideotape/propFileRecord.inc.c>
    #include <assets/obseg/prop/nintendologo/propFileRecord.inc.c>
    #include <assets/obseg/prop/goldeneyelogo/propFileRecord.inc.c>
    #include <assets/obseg/prop/walletbond/propFileRecord.inc.c>
    #include <assets/obseg/prop/miltruck/propFileRecord.inc.c>
    #include <assets/obseg/prop/jeep/propFileRecord.inc.c>
    #include <assets/obseg/prop/artic/propFileRecord.inc.c>
    #include <assets/obseg/prop/helicopter/propFileRecord.inc.c>
    #include <assets/obseg/prop/tiger/propFileRecord.inc.c>
    #include <assets/obseg/prop/milcopter/propFileRecord.inc.c>
    #include <assets/obseg/prop/hind/propFileRecord.inc.c>
    #include <assets/obseg/prop/artictrailer/propFileRecord.inc.c>
    #include <assets/obseg/prop/motorbike/propFileRecord.inc.c>
    #include <assets/obseg/prop/tank/propFileRecord.inc.c>
    #include <assets/obseg/prop/apc/propFileRecord.inc.c>
    #include <assets/obseg/prop/speedboat/propFileRecord.inc.c>
    #include <assets/obseg/prop/plane/propFileRecord.inc.c>
    #include <assets/obseg/prop/gun_runway1/propFileRecord.inc.c>
    #include <assets/obseg/prop/safedoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/key_holder/propFileRecord.inc.c>
    #include <assets/obseg/prop/hatchsevx/propFileRecord.inc.c>
    #include <assets/obseg/prop/sevdish/propFileRecord.inc.c>
    #include <assets/obseg/prop/archsecdoor1/propFileRecord.inc.c>
    #include <assets/obseg/prop/archsecdoor2/propFileRecord.inc.c>
    #include <assets/obseg/prop/groundgun/propFileRecord.inc.c>
    #include <assets/obseg/prop/trainextdoor/propFileRecord.inc.c>
    #include <assets/obseg/prop/carbmw/propFileRecord.inc.c>
    #include <assets/obseg/prop/carescort/propFileRecord.inc.c>
    #include <assets/obseg/prop/cargolf/propFileRecord.inc.c>
    #include <assets/obseg/prop/carweird/propFileRecord.inc.c>
    #include <assets/obseg/prop/carzil/propFileRecord.inc.c>
    #include <assets/obseg/prop/shuttle_door_l/propFileRecord.inc.c>
    #include <assets/obseg/prop/shuttle_door_r/propFileRecord.inc.c>
    #include <assets/obseg/prop/depot_gate_entry/propFileRecord.inc.c>
    #include <assets/obseg/prop/depot_door_steel/propFileRecord.inc.c>
    #include <assets/obseg/prop/glassware2/propFileRecord.inc.c>
    #include <assets/obseg/prop/glassware3/propFileRecord.inc.c>
    #include <assets/obseg/prop/glassware4/propFileRecord.inc.c>
    #include <assets/obseg/prop/landmine/propFileRecord.inc.c>
    #include <assets/obseg/prop/plant1/propFileRecord.inc.c>
    #include <assets/obseg/prop/plant11/propFileRecord.inc.c>
    #include <assets/obseg/prop/plant2/propFileRecord.inc.c>
    #include <assets/obseg/prop/plant3/propFileRecord.inc.c>
    #include <assets/obseg/prop/jungle5_tree/propFileRecord.inc.c>
    #include <assets/obseg/prop/legalpage/propFileRecord.inc.c>
    #include <assets/obseg/prop/st_pete_room_1i/propFileRecord.inc.c>
    #include <assets/obseg/prop/st_pete_room_2i/propFileRecord.inc.c>
    #include <assets/obseg/prop/st_pete_room_3t/propFileRecord.inc.c>
    #include <assets/obseg/prop/st_pete_room_5c/propFileRecord.inc.c>
    #include <assets/obseg/prop/st_pete_room_6c/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_rollertrain/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_win/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_aztec/propFileRecord.inc.c>
    #include <assets/obseg/prop/shuttle/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_azt_desk/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_azt_desk_top/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_azt_chair/propFileRecord.inc.c>
    #include <assets/obseg/prop/door_mf/propFileRecord.inc.c>
    #include <assets/obseg/prop/flag/propFileRecord.inc.c>
    #include <assets/obseg/prop/barricade/propFileRecord.inc.c>
    #include <assets/obseg/prop/modembox/propFileRecord.inc.c>
    #include <assets/obseg/prop/doorpanel/propFileRecord.inc.c>
    #include <assets/obseg/prop/doorconsole/propFileRecord.inc.c>
    #include <assets/obseg/prop/chrtesttube/propFileRecord.inc.c>
    #include <assets/obseg/prop/bollard/propFileRecord.inc.c>
    {0, "", 1.0}
};
