struct ChrModelFileRecord c_item_entries[] = {
    #include <assets/obseg/chr/camguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/greyguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/oliveguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/rusguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/trevguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/djbond/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/boris/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/orumov/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/trevelyan/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/boilertrev/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/valentin/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/xenia/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/baronsamedi/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/jaws/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/mayday/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/oddjob/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/natalya/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/armourguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/commguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/greatguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/navyguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/snowguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/boilerbond/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/suitbond/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/timberbond/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/snowbond/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/bluewoman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/fattechwoman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/techwoman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/jeanwoman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/greyman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/blueman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/redman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/cardiman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/checkman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/techman/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/pilot/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/greatguard2/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/bluecamguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/moonguard/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/moonfemale/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/suit_lf_hand/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headkarl/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headalan/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headpete/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headmartin/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headmark/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headduncan/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headshaun/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headdwayne/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headb/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headdave/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headgrant/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headdes/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headchris/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headlee/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headneil/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headjim/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headrobin/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headsteveh/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headbalaclava/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headbike/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headgraham/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headstevee/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headjoel/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headscott/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headjoe/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headken/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headjoe2/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headmishkin/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headsally/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headmarion/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headmandy/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headvivien/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headbrosnanboiler/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headbrosnansuit/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headbrosnantimber/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headbrosnansnow/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/headbrosnan/chrModelFileRecord.inc.c>
    #include <assets/obseg/chr/spicebond/chrModelFileRecord.inc.c>
    {0, 0, 1.0, 0.0, 0x00, 0x00, 0x00, 0x00}
};
